# Generated by Django 3.1 on 2022-05-18 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_appreciation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appreciation',
            old_name='observation',
            new_name='appreciation',
        ),
        migrations.AddField(
            model_name='appreciation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
